ffmuc-mesh-vpn-wireguard: enable loadbalancing (#100)
* ffmuc-mesh-vpn-wireguard: Add support for the server-side loadbalancing with wgkex v0.2.0+
---------

Co-authored-by: Grische <2787581+grische@users.noreply.github.com>
Co-authored-by: DasSkelett <dasskelett@gmail.com>
Co-authored-by: Tobias <tobias-m99@gmx.de>

diff --git a/ffmuc-mesh-vpn-wireguard-vxlan/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink b/ffmuc-mesh-vpn-wireguard-vxlan/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
--- a/ffmuc-mesh-vpn-wireguard-vxlan/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
+++ b/ffmuc-mesh-vpn-wireguard-vxlan/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
@@ -11,6 +11,28 @@ else
 	exit
 fi
 
+get_site_string() {
+	local path="$1"
+
+	lua <<EOF
+local site = require 'gluon.site'
+print(site.${path}())
+EOF
+}
+
+get_site_bool() {
+	local path="$1"
+
+	lua <<EOF
+local site = require 'gluon.site'
+if site.${path}() then
+    print("true")
+else
+	print("false")
+end
+EOF
+}
+
 interface_linklocal() {
 	# We generate a predictable v6 address
 	local macaddr oldIFS
@@ -27,27 +49,131 @@ clean_port() {
 	echo "$1" | sed -r 's/:[0-9]+$|\[|\]//g'
 }
 
-check_address_family() {
-	local peer_endpoint="$2"
-	local gateway
-	gateway="$(clean_port "$peer_endpoint")"
+extract_port() {
+    echo "$1" | awk -F: '{print $NF}'
+}
+
+combine_ip_port() {
+    local ip="$1"
+    local port="$2"
+
+    # Add brackets in case the IP is an IPv6
+    case $ip in
+        *":"*)
+            ip="[${ip}]"
+            ;;
+    esac
+
+    echo "$ip:$port"
+}
+
+resolve_host() {
+	local gateway="$1"
 	# Check if we have a default route for v6 if not fallback to v4
 	if ip -6 route show table 1 | grep -q 'default via'
 	then
 		local ipv6
-		ipv6="$(gluon-wan nslookup "$gateway" | grep 'Address:\? [0-9]' | grep -E -o '([a-f0-9:]+:+)+[a-f0-9]+')"
-		echo "[$ipv6]$(echo "$peer_endpoint" | grep -E -oe ":[0-9]+$")"
+		ipv6="$(gluon-wan nslookup "$gateway" | grep 'Address:\? [0-9]' | grep -oE '([a-f0-9:]+:+)+[a-f0-9]+')"
+		echo "$ipv6"
 	else
 		local ipv4
-		ipv4="$(gluon-wan nslookup "$gateway" | grep 'Address:\? [0-9]' | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")"
-		echo "$ipv4$(echo "$peer_endpoint" | grep -E -oe ":[0-9]+$")"
+		ipv4="$(gluon-wan nslookup "$gateway" | grep 'Address:\? [0-9]' | grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b')"
+		echo "$ipv4"
 	fi
-
 }
 
 force_wan_connection() {
 	LD_PRELOAD=libpacketmark.so LIBPACKETMARK_MARK=1 gluon-wan "$@"
 }
+
+is_loadbalancing_enabled() {
+	local lb_default
+	local lb_overwrite
+	lb_default=$(get_site_string mesh_vpn.wireguard.loadbalancing)
+
+	if [[ $lb_default == "on" ]]; then
+		return 0 # true
+	elif [[ $lb_default == "off" ]]; then
+		return 1 # false
+	fi
+
+	# check if an overwrite was specified
+	if lb_overwrite=$(uci -q get wireguard.mesh_vpn.loadbalancing); then
+		logger -p info -t checkuplink "Loadbalancing overwrite detected: ${lb_overwrite}"
+		if [[ $lb_overwrite == "1" ]]; then
+			return 0 # true
+		elif [[ $lb_overwrite == "0" ]]; then
+			return 1 # false
+		fi
+	fi
+
+	if [[ $lb_default == "on-by-default" ]]; then
+		return 0 # true
+	elif [[ $lb_default == "off-by-default" ]]; then
+		return 1 # false
+	fi
+
+	logger -p err -t checkuplink "Invalid loadbalancing parameter '${lb_default}', assuming 'off'"
+	return 0
+}
+
+get_wgkex_data(){
+	local version="$1"
+	WGKEX_BROKER="$PROTO://$WGKEX_BROKER_BASE_PATH/api/$version/wg/key/exchange"
+
+	logger -p info -t checkuplink "Contacting wgkex broker $WGKEX_BROKER"
+
+	if ! WGKEX_DATA=$(force_wan_connection wget -q -O- --post-data='{"domain": "'"$SEGMENT"'","public_key": "'"$PUBLICKEY"'"}' "$WGKEX_BROKER"); then
+		logger -p err -t checkuplink "Contacting wgkex broker failed, response: $WGKEX_DATA"
+		return 1
+	fi
+
+	logger -p info -t checkuplink "Got data from wgkex broker: $WGKEX_DATA"
+	echo "$WGKEX_DATA"
+}
+
+use_api_v1(){
+	WGKEX_DATA=$(get_wgkex_data v1)
+
+	# Get the number of configured peers and randomly select one
+	NUMBER_OF_PEERS=$(uci -q show wireguard | grep -E -ce "peer_[0-9]+.endpoint")
+	PEER="$(awk -v min=1 -v max="$NUMBER_OF_PEERS" 'BEGIN{srand(); print int(min+rand()*(max-min+1))}')"
+
+	logger -p info -t checkuplink "Selected peer $PEER"
+	PEER_HOSTPORT="$(uci get wireguard.peer_"$PEER".endpoint)"
+	PEER_HOST="$(clean_port "$PEER_HOSTPORT")"
+	PEER_ADDRESS="$(resolve_host "$PEER_HOST")"
+	PEER_PORT="$(extract_port "$PEER_HOSTPORT")"
+	PEER_ENDPOINT="$(combine_ip_port "$PEER_ADDRESS" "$PEER_PORT")"
+
+	PEER_PUBLICKEY="$(uci get wireguard.peer_"$PEER".publickey)"
+	PEER_LINKADDRESS="$(uci get wireguard.peer_"$PEER".link_address)"
+}
+
+
+
+use_api_v2() {
+	WGKEX_DATA=$(get_wgkex_data v2)
+
+	# Parse the returned JSON in a Lua script, returning the endpoint address, port, pubkey and first allowed IP, separated by newlines
+	if ! data=$(lua /lib/gluon/gluon-mesh-wireguard-vxlan/parse-wgkex-response.lua "$WGKEX_DATA"); then
+		logger -p err -t checkuplink "Parsing wgkex broker data failed"
+		logger -p info -t checkuplink "Falling back to API v1"
+		use_api_v1
+		return
+	fi
+
+	logger -p debug -t checkuplink "Successfully parsed wgkex broker data"
+	PEER_HOST="$(echo "$data" | sed -n 1p)"
+	PEER_PORT="$(echo "$data" | sed -n 2p)"
+	PEER_PUBLICKEY="$(echo "$data" | sed -n 3p)"
+	PEER_LINKADDRESS=$(echo "$data" | sed -n 4p)
+
+	PEER_ADDRESS="$(resolve_host "$PEER_HOST")"
+	PEER_ENDPOINT="$(combine_ip_port "$PEER_ADDRESS" "$PEER_PORT")"
+}
+
+
 
 
 mesh_vpn_enabled="$(uci get wireguard.mesh_vpn.enabled)"
@@ -76,7 +202,7 @@ fi
 #We assume we are not connected by default
 CONNECTED=0
 
-MESH_VPN_IFACE=$(uci get wireguard.mesh_vpn.iface)
+MESH_VPN_IFACE=$(get_site_string mesh_vpn.wireguard.iface)
 
 # Check connectivity to supernode
 
@@ -125,17 +251,6 @@ then
 	exit 3
 fi
 
-# Get the number of configured peers and randomly select one
-NUMBER_OF_PEERS=$(uci -q show wireguard | grep -E -ce "peer_[0-9]+.endpoint")
-PEER="$(awk -v min=1 -v max="$NUMBER_OF_PEERS" 'BEGIN{srand(); print int(min+rand()*(max-min+1))}')"
-PEER_PUBLICKEY="$(uci get wireguard.peer_"$PEER".publickey)"
-
-logger -t checkuplink "Selected peer $PEER"
-
-endpoint="$(check_address_family "$PEER_PUBLICKEY" "$(uci get wireguard.peer_"$PEER".endpoint)")"
-
-logger -t checkuplink "Connecting to $endpoint"
-
 # Delete Interfaces
 {
 	ip link set nomaster dev mesh-vpn >/dev/null 2>&1
@@ -146,7 +261,7 @@ ip link delete dev "${MESH_VPN_IFACE}" >/dev/null 2>&1 || true
 PUBLICKEY=$(uci get wireguard.mesh_vpn.privatekey | wg pubkey)
 SEGMENT=$(uci get gluon.core.domain)
 
-# Push public key to broker, test for https and use if supported
+# Push public key to broker and receive gateway data, test for https and use if supported
 ret=0
 wget -q "https://[::1]" || ret=$?
 # returns Network Failure =4 if https exists
@@ -156,7 +271,22 @@ if [ "$ret" -eq 1 ]; then
 else
 	PROTO=https
 fi
-force_wan_connection wget -q  -O- --post-data='{"domain": "'"$SEGMENT"'","public_key": "'"$PUBLICKEY"'"}' "$PROTO://$(uci get wireguard.mesh_vpn.broker)"
+
+# Remove API path suffix if still present in config
+WGKEX_BROKER_BASE_PATH="$(get_site_string mesh_vpn.wireguard.broker | sed 's|/api/v1/wg/key/exchange||')"
+
+if is_loadbalancing_enabled; then
+	# Use /api/v2, get gateway peer details from broker response
+	logger -p info -t checkuplink "Loadbalancing enabled."
+	use_api_v2
+
+else
+	# Use /api/v1, get gateway peer details from config
+	logger -p info -t checkuplink "Loadbalancing disabled."
+	use_api_v1
+fi
+
+logger -p info -t checkuplink "Connecting to $PEER_HOST($PEER_ENDPOINT)"
 
 # Bring up the wireguard interface
 ip link add dev "$MESH_VPN_IFACE" type wireguard
@@ -168,10 +298,7 @@ LINKLOCAL="$(interface_linklocal)"
 
 # Add link-address and Peer
 ip address add "${LINKLOCAL}"/64 dev "$MESH_VPN_IFACE"
-if [ "$endpoint" = "" ]; then
-	endpoint=$(uci get wireguard.peer_"$PEER".endpoint)
-fi
-gluon-wan wg set "$MESH_VPN_IFACE" peer "$(uci get wireguard.peer_"$PEER".publickey)" persistent-keepalive 25 allowed-ips "$(uci get wireguard.peer_"$PEER".link_address)/128" endpoint "$endpoint"
+gluon-wan wg set "$MESH_VPN_IFACE" peer "$PEER_PUBLICKEY" persistent-keepalive 25 allowed-ips "$PEER_LINKADDRESS/128" endpoint "$PEER_ENDPOINT"
 
 # We need to allow incoming vxlan traffic on mesh iface
 sleep 10
@@ -184,7 +311,7 @@ then
 fi
 
 # Bring up VXLAN
-if ! ip link add mesh-vpn type vxlan id "$(lua -e 'print(tonumber(require("gluon.util").domain_seed_bytes("gluon-mesh-vpn-vxlan", 3), 16))')" local "${LINKLOCAL}" remote "$(uci get wireguard.peer_"$PEER".link_address)" dstport 8472 dev "$MESH_VPN_IFACE"
+if ! ip link add mesh-vpn type vxlan id "$(lua -e 'print(tonumber(require("gluon.util").domain_seed_bytes("gluon-mesh-vpn-vxlan", 3), 16))')" local "${LINKLOCAL}" remote "$PEER_LINKADDRESS" dstport 8472 dev "$MESH_VPN_IFACE"
 then
 	logger -p err -t checkuplink "Unable to create mesh-vpn interface"
 	exit 2
